### PR TITLE
Add spanish translations

### PR DESCRIPTION
**Pull request by facine**

### CODE REVIEW

**Comment by ParisLiakos** [comment]
Are them the same? if yes, having just "es" is enough. 
We just need to make it fallback to "es" if there is no translation for "es_ES" or "es_XX"

**Comment by facine** [comment]
Yes are the same, how can I do this?

Thanks

**Comment by ParisLiakos** [comment]
I think it already works like that.. I just checked: Added "es" translations, with "es" locale. Everything is correct. Then i changed my locale to "es_AR", logged out and then back in. Still the "es" translation where displayed :)
So, all you have to do is, remove es_ES translations here and i will merge this.

Cheers!

**Comment by facine** [comment]
Doned!

Thanks!

**Pull request merged**
