### PR TITLE
Default templates - Spanish version

### PR DESCRIPTION
**Pull request by JMCA2**
The bundled default invoice and estimate templates, translated into Spanish. Might be useful for some people, so they don't need to manually translate them.
They are added as `print.es.html.twig` files.

Since at the moment is not possible to select from different templates in the app interface, I think it would be ok for now to just add to the wiki something like:

> "If you wish to use the translated version of the default templates, rename 'print.es.html.twig' to 'print.html.twig' on both `src/Siwapp/InvoiceBundle/Resources/views/Invoice/` and `src/Siwapp/EstimateBundle/Resources/views/Estimate/`.

### CODE REVIEW

**Comment by ParisLiakos** [comment]
Ah...print templates are not translatable. We should make them translatable with twig's `{% trans %}` and then translate it normally just other strings

**Comment by JMCA2** [comment]
I think it would make more sense to just add the option to select from multiple templates. The old app allowed that, so people can use different designs without having to modify the default template file

**Comment by JMCA2** [comment]
Then the spanish default template could be another template to choose from

**Comment by ParisLiakos** [comment]
Yes, choosing between multiple designs - i agree. But choosing between languages - no. Each design template should be translatable to all languages using the normal translation procedure ;)
Otherwise we would need one template per language - per design. It wouldnt scale well

**Comment by JMCA2** [comment]
You're right, it makes more sense that way 👍

**Comment by ParisLiakos** [comment]
I have pushed b9c9019b2e95b635666f89d5091eefe2fa006323
Does it cover this?

**Comment by ParisLiakos** [comment]
Can you remove the twig templates from this pull request?

**Comment by JMCA2** [comment]
I'll take care of this soon

**Comment by JMCA2** [comment]
Twig templates removed 👍

**Comment by ParisLiakos** [comment]
Thanks!

**Pull request merged**
