### PR TITLE
Slightly increase form field width

### LINKED ISSUE #81: [CSS] Discount value doesn't fit on field
captura

The full default discount % (0.00) should be shown in the field, currently the third number doesn't fit.

### PR DESCRIPTION
**Pull request by JMCA2**
Fixes #81

### CODE REVIEW

**Comment by ParisLiakos** [comment]
I think we should only override the col-md class for this table and not globally.
Maybe prefix it with .invoice-like ? Or we could even introduce a new class for this table

**Comment by ParisLiakos** [comment]
Ah, right, that works better, thanks!

**Comment by JMCA2** [comment]
Please increase the 8.78% to 9.0% as before, 8.78 is not enough

**Comment by ParisLiakos** [comment]
done

**Comment by JMCA2** [comment]
Great. Thanks!

**Pull request merged**
